name: Content.Engine
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Execute Engine
      env:
        R2_BUCKET_NAME: data
        R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
        R2_API_TOKEN: ${{ secrets.R2_API_TOKEN }}
      run: |
        PROJECT_PATH=$(find . -name "CLEngine.csproj" | head -n 1)
        PROJECT_DIR=$(dirname "$PROJECT_PATH")
        cd "$PROJECT_DIR"
        dotnet restore
        dotnet run --configuration Release
